
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mcscjunjie.junzulaki.trafficmod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import mcscjunjie.junzulaki.trafficmod.JunjietrafficmodMod;

public class JunjietrafficmodModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, JunjietrafficmodMod.MODID);
	public static final RegistryObject<CreativeModeTab> TLIGHT = REGISTRY.register("tlight",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.junjietrafficmod.tlight")).icon(() -> new ItemStack(Blocks.MAGENTA_GLAZED_TERRACOTTA)).displayItems((parameters, tabData) -> {
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_4.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.BASSBLUE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.BASSWHITE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.PILLARBLUE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.PILLARWHITE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORDRIVETIREDLY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORREAREND.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORKEEPSPACE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORKEEP_0.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORKEEP_15.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HORKEEP_30.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_2KM.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_1KM.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CARMODELLIMITPART_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CARMODELLIMITPART_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CARMODELLIMIT_ADDON.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_5.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_6.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_R.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_L_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_L_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TLIGHT_L_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.PILLAR_CROSS_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.PILLAR_SIDE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SIDEDRIVETIREDLY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SIDEREAREND.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SIDEKEEPSPACE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_PILLAR_BASE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_PILLAR_HIGH.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITG.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITS.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITXY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITR.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITN.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXIT_3KM.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXIT_2KM.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXIT_1KM.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXIT_500M.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITNOW.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_G.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_S.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_XY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_SIDE_G.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_SIDE_S.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_SIDE_XY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXPWY_G.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXPWY_S.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.MILEAGE_R.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.MILEAGE_RG.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.MILEAGE_RS.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.MILEAGE_RXY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.MILEAGE_RN.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_PILLAR_TOP.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LIMIT_CAR.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LIMIT_TRUCK.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LIMIT_EMERGENCY.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_PILE_NUMBER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_1_G.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_1_S.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_3500M.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_3R.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ENTRANCE_E_3L.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.FWQ_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.FWQ_21.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.FWQ_22.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LEFT_ARROW.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LEFT_ARROW_SIDE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.RIGHT_ARROW.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.RIGHT_ARROW_SIDE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.STRAIGHT_ARROW.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.STRAIGHT_ARROW_SIDE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_EXPWY_GNUMBER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_EXPWY_SNUMBER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_EXPWY_BEGIN.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_EXPWY_END.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_A_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_A_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_B_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.INTERCHANGE_B_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SEATBELT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.HO_RPLACEREPORT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.STRICT_ROAD.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ECROSS_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ECROSS_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ECROSS_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ECROSS_4.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ENOPHONE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ETOLLGATE_500M.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ETOLLGATE_0M.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_EWEIGHINGSTATION.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_EBARRIER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_ETUNNEL.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SID_EEXITNUMBER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_4.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_5.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_6.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CROSS_7.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_4.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_5.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_6.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_7.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_8.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_9.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_10.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_11.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_12.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_13.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TIP_14.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.WATER_PROTECT_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.WATER_PROTECT_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.WATER_PROTECT_3.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.WATER_PROTECT_4.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GUO_3NOOUT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.TRUCKRIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CALLPHONE_1.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.CALLPHONE_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.BAD_WEATHER.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.LAND_SLIDE_AREA.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.BRIDGE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXITREPORT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.NEXTEXIT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.STRICT_ROAD_2.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.SERVICE_AREA_ENTRANCE.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXIT_NUMBER_SHOW.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXPWY_EXIT_STRAIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.EXPWY_EXIT_RIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_EXIT_STRAIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.ROAD_EXIT_RIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_G_INTER_STRAIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_G_INTER_RIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_G_INTER_LEFT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_S_INTER_STRAIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_S_INTER_RIGHT.get().asItem());
				tabData.accept(JunjietrafficmodModBlocks.GANTRY_S_INTER_LEFT.get().asItem());
			})

					.build());
}
