
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mcscjunjie.junzulaki.trafficmod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import mcscjunjie.junzulaki.trafficmod.JunjietrafficmodMod;

public class JunjietrafficmodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, JunjietrafficmodMod.MODID);
	public static final RegistryObject<Item> TLIGHT_1 = block(JunjietrafficmodModBlocks.TLIGHT_1);
	public static final RegistryObject<Item> TLIGHT_2 = block(JunjietrafficmodModBlocks.TLIGHT_2);
	public static final RegistryObject<Item> TLIGHT_3 = block(JunjietrafficmodModBlocks.TLIGHT_3);
	public static final RegistryObject<Item> TLIGHT_4 = block(JunjietrafficmodModBlocks.TLIGHT_4);
	public static final RegistryObject<Item> BASSBLUE = block(JunjietrafficmodModBlocks.BASSBLUE);
	public static final RegistryObject<Item> BASSWHITE = block(JunjietrafficmodModBlocks.BASSWHITE);
	public static final RegistryObject<Item> PILLARBLUE = block(JunjietrafficmodModBlocks.PILLARBLUE);
	public static final RegistryObject<Item> PILLARWHITE = block(JunjietrafficmodModBlocks.PILLARWHITE);
	public static final RegistryObject<Item> HORDRIVETIREDLY = block(JunjietrafficmodModBlocks.HORDRIVETIREDLY);
	public static final RegistryObject<Item> HORREAREND = block(JunjietrafficmodModBlocks.HORREAREND);
	public static final RegistryObject<Item> HORKEEPSPACE = block(JunjietrafficmodModBlocks.HORKEEPSPACE);
	public static final RegistryObject<Item> HORKEEP_0 = block(JunjietrafficmodModBlocks.HORKEEP_0);
	public static final RegistryObject<Item> HORKEEP_15 = block(JunjietrafficmodModBlocks.HORKEEP_15);
	public static final RegistryObject<Item> HORKEEP_30 = block(JunjietrafficmodModBlocks.HORKEEP_30);
	public static final RegistryObject<Item> INTERCHANGE_2KM = block(JunjietrafficmodModBlocks.INTERCHANGE_2KM);
	public static final RegistryObject<Item> INTERCHANGE_1KM = block(JunjietrafficmodModBlocks.INTERCHANGE_1KM);
	public static final RegistryObject<Item> CARMODELLIMITPART_1 = block(JunjietrafficmodModBlocks.CARMODELLIMITPART_1);
	public static final RegistryObject<Item> CARMODELLIMITPART_2 = block(JunjietrafficmodModBlocks.CARMODELLIMITPART_2);
	public static final RegistryObject<Item> CARMODELLIMIT_ADDON = block(JunjietrafficmodModBlocks.CARMODELLIMIT_ADDON);
	public static final RegistryObject<Item> TLIGHT_5 = block(JunjietrafficmodModBlocks.TLIGHT_5);
	public static final RegistryObject<Item> TLIGHT_6 = block(JunjietrafficmodModBlocks.TLIGHT_6);
	public static final RegistryObject<Item> TLIGHT_R = block(JunjietrafficmodModBlocks.TLIGHT_R);
	public static final RegistryObject<Item> TLIGHT_L_1 = block(JunjietrafficmodModBlocks.TLIGHT_L_1);
	public static final RegistryObject<Item> TLIGHT_L_2 = block(JunjietrafficmodModBlocks.TLIGHT_L_2);
	public static final RegistryObject<Item> TLIGHT_L_3 = block(JunjietrafficmodModBlocks.TLIGHT_L_3);
	public static final RegistryObject<Item> PILLAR_CROSS_3 = block(JunjietrafficmodModBlocks.PILLAR_CROSS_3);
	public static final RegistryObject<Item> PILLAR_SIDE = block(JunjietrafficmodModBlocks.PILLAR_SIDE);
	public static final RegistryObject<Item> SIDEDRIVETIREDLY = block(JunjietrafficmodModBlocks.SIDEDRIVETIREDLY);
	public static final RegistryObject<Item> SIDEREAREND = block(JunjietrafficmodModBlocks.SIDEREAREND);
	public static final RegistryObject<Item> SIDEKEEPSPACE = block(JunjietrafficmodModBlocks.SIDEKEEPSPACE);
	public static final RegistryObject<Item> GANTRY_PILLAR_BASE = block(JunjietrafficmodModBlocks.GANTRY_PILLAR_BASE);
	public static final RegistryObject<Item> GANTRY_PILLAR_HIGH = block(JunjietrafficmodModBlocks.GANTRY_PILLAR_HIGH);
	public static final RegistryObject<Item> EXITG = block(JunjietrafficmodModBlocks.EXITG);
	public static final RegistryObject<Item> EXITS = block(JunjietrafficmodModBlocks.EXITS);
	public static final RegistryObject<Item> EXITXY = block(JunjietrafficmodModBlocks.EXITXY);
	public static final RegistryObject<Item> EXITR = block(JunjietrafficmodModBlocks.EXITR);
	public static final RegistryObject<Item> EXITN = block(JunjietrafficmodModBlocks.EXITN);
	public static final RegistryObject<Item> EXIT_3KM = block(JunjietrafficmodModBlocks.EXIT_3KM);
	public static final RegistryObject<Item> EXIT_2KM = block(JunjietrafficmodModBlocks.EXIT_2KM);
	public static final RegistryObject<Item> EXIT_1KM = block(JunjietrafficmodModBlocks.EXIT_1KM);
	public static final RegistryObject<Item> EXIT_500M = block(JunjietrafficmodModBlocks.EXIT_500M);
	public static final RegistryObject<Item> EXITNOW = block(JunjietrafficmodModBlocks.EXITNOW);
	public static final RegistryObject<Item> ROAD_G = block(JunjietrafficmodModBlocks.ROAD_G);
	public static final RegistryObject<Item> ROAD_S = block(JunjietrafficmodModBlocks.ROAD_S);
	public static final RegistryObject<Item> ROAD_XY = block(JunjietrafficmodModBlocks.ROAD_XY);
	public static final RegistryObject<Item> ROAD_SIDE_G = block(JunjietrafficmodModBlocks.ROAD_SIDE_G);
	public static final RegistryObject<Item> ROAD_SIDE_S = block(JunjietrafficmodModBlocks.ROAD_SIDE_S);
	public static final RegistryObject<Item> ROAD_SIDE_XY = block(JunjietrafficmodModBlocks.ROAD_SIDE_XY);
	public static final RegistryObject<Item> EXPWY_G = block(JunjietrafficmodModBlocks.EXPWY_G);
	public static final RegistryObject<Item> EXPWY_S = block(JunjietrafficmodModBlocks.EXPWY_S);
	public static final RegistryObject<Item> MILEAGE_R = block(JunjietrafficmodModBlocks.MILEAGE_R);
	public static final RegistryObject<Item> MILEAGE_RG = block(JunjietrafficmodModBlocks.MILEAGE_RG);
	public static final RegistryObject<Item> MILEAGE_RS = block(JunjietrafficmodModBlocks.MILEAGE_RS);
	public static final RegistryObject<Item> MILEAGE_RXY = block(JunjietrafficmodModBlocks.MILEAGE_RXY);
	public static final RegistryObject<Item> MILEAGE_RN = block(JunjietrafficmodModBlocks.MILEAGE_RN);
	public static final RegistryObject<Item> GANTRY_PILLAR_TOP = block(JunjietrafficmodModBlocks.GANTRY_PILLAR_TOP);
	public static final RegistryObject<Item> LIMIT_CAR = block(JunjietrafficmodModBlocks.LIMIT_CAR);
	public static final RegistryObject<Item> LIMIT_TRUCK = block(JunjietrafficmodModBlocks.LIMIT_TRUCK);
	public static final RegistryObject<Item> LIMIT_EMERGENCY = block(JunjietrafficmodModBlocks.LIMIT_EMERGENCY);
	public static final RegistryObject<Item> GANTRY_PILE_NUMBER = block(JunjietrafficmodModBlocks.GANTRY_PILE_NUMBER);
	public static final RegistryObject<Item> ENTRANCE_E_1_G = block(JunjietrafficmodModBlocks.ENTRANCE_E_1_G);
	public static final RegistryObject<Item> ENTRANCE_E_1_S = block(JunjietrafficmodModBlocks.ENTRANCE_E_1_S);
	public static final RegistryObject<Item> ENTRANCE_E_2 = block(JunjietrafficmodModBlocks.ENTRANCE_E_2);
	public static final RegistryObject<Item> ENTRANCE_E_3500M = block(JunjietrafficmodModBlocks.ENTRANCE_E_3500M);
	public static final RegistryObject<Item> ENTRANCE_E_3R = block(JunjietrafficmodModBlocks.ENTRANCE_E_3R);
	public static final RegistryObject<Item> ENTRANCE_E_3L = block(JunjietrafficmodModBlocks.ENTRANCE_E_3L);
	public static final RegistryObject<Item> FWQ_1 = block(JunjietrafficmodModBlocks.FWQ_1);
	public static final RegistryObject<Item> FWQ_21 = block(JunjietrafficmodModBlocks.FWQ_21);
	public static final RegistryObject<Item> FWQ_22 = block(JunjietrafficmodModBlocks.FWQ_22);
	public static final RegistryObject<Item> LEFT_ARROW = block(JunjietrafficmodModBlocks.LEFT_ARROW);
	public static final RegistryObject<Item> LEFT_ARROW_SIDE = block(JunjietrafficmodModBlocks.LEFT_ARROW_SIDE);
	public static final RegistryObject<Item> RIGHT_ARROW = block(JunjietrafficmodModBlocks.RIGHT_ARROW);
	public static final RegistryObject<Item> RIGHT_ARROW_SIDE = block(JunjietrafficmodModBlocks.RIGHT_ARROW_SIDE);
	public static final RegistryObject<Item> STRAIGHT_ARROW = block(JunjietrafficmodModBlocks.STRAIGHT_ARROW);
	public static final RegistryObject<Item> STRAIGHT_ARROW_SIDE = block(JunjietrafficmodModBlocks.STRAIGHT_ARROW_SIDE);
	public static final RegistryObject<Item> GANTRY_EXPWY_GNUMBER = block(JunjietrafficmodModBlocks.GANTRY_EXPWY_GNUMBER);
	public static final RegistryObject<Item> GANTRY_EXPWY_SNUMBER = block(JunjietrafficmodModBlocks.GANTRY_EXPWY_SNUMBER);
	public static final RegistryObject<Item> GANTRY_EXPWY_BEGIN = block(JunjietrafficmodModBlocks.GANTRY_EXPWY_BEGIN);
	public static final RegistryObject<Item> GANTRY_EXPWY_END = block(JunjietrafficmodModBlocks.GANTRY_EXPWY_END);
	public static final RegistryObject<Item> INTERCHANGE_A_1 = block(JunjietrafficmodModBlocks.INTERCHANGE_A_1);
	public static final RegistryObject<Item> INTERCHANGE_A_2 = block(JunjietrafficmodModBlocks.INTERCHANGE_A_2);
	public static final RegistryObject<Item> INTERCHANGE_B_1 = block(JunjietrafficmodModBlocks.INTERCHANGE_B_1);
	public static final RegistryObject<Item> INTERCHANGE_B_2 = block(JunjietrafficmodModBlocks.INTERCHANGE_B_2);
	public static final RegistryObject<Item> SEATBELT = block(JunjietrafficmodModBlocks.SEATBELT);
	public static final RegistryObject<Item> HO_RPLACEREPORT = block(JunjietrafficmodModBlocks.HO_RPLACEREPORT);
	public static final RegistryObject<Item> STRICT_ROAD = block(JunjietrafficmodModBlocks.STRICT_ROAD);
	public static final RegistryObject<Item> SID_ECROSS_1 = block(JunjietrafficmodModBlocks.SID_ECROSS_1);
	public static final RegistryObject<Item> SID_ECROSS_2 = block(JunjietrafficmodModBlocks.SID_ECROSS_2);
	public static final RegistryObject<Item> SID_ECROSS_3 = block(JunjietrafficmodModBlocks.SID_ECROSS_3);
	public static final RegistryObject<Item> SID_ECROSS_4 = block(JunjietrafficmodModBlocks.SID_ECROSS_4);
	public static final RegistryObject<Item> SID_ENOPHONE = block(JunjietrafficmodModBlocks.SID_ENOPHONE);
	public static final RegistryObject<Item> SID_ETOLLGATE_500M = block(JunjietrafficmodModBlocks.SID_ETOLLGATE_500M);
	public static final RegistryObject<Item> SID_ETOLLGATE_0M = block(JunjietrafficmodModBlocks.SID_ETOLLGATE_0M);
	public static final RegistryObject<Item> SID_EWEIGHINGSTATION = block(JunjietrafficmodModBlocks.SID_EWEIGHINGSTATION);
	public static final RegistryObject<Item> SID_EBARRIER = block(JunjietrafficmodModBlocks.SID_EBARRIER);
	public static final RegistryObject<Item> SID_ETUNNEL = block(JunjietrafficmodModBlocks.SID_ETUNNEL);
	public static final RegistryObject<Item> SID_EEXITNUMBER = block(JunjietrafficmodModBlocks.SID_EEXITNUMBER);
	public static final RegistryObject<Item> CROSS_1 = block(JunjietrafficmodModBlocks.CROSS_1);
	public static final RegistryObject<Item> CROSS_2 = block(JunjietrafficmodModBlocks.CROSS_2);
	public static final RegistryObject<Item> CROSS_3 = block(JunjietrafficmodModBlocks.CROSS_3);
	public static final RegistryObject<Item> CROSS_4 = block(JunjietrafficmodModBlocks.CROSS_4);
	public static final RegistryObject<Item> CROSS_5 = block(JunjietrafficmodModBlocks.CROSS_5);
	public static final RegistryObject<Item> CROSS_6 = block(JunjietrafficmodModBlocks.CROSS_6);
	public static final RegistryObject<Item> CROSS_7 = block(JunjietrafficmodModBlocks.CROSS_7);
	public static final RegistryObject<Item> TIP_1 = block(JunjietrafficmodModBlocks.TIP_1);
	public static final RegistryObject<Item> TIP_2 = block(JunjietrafficmodModBlocks.TIP_2);
	public static final RegistryObject<Item> TIP_3 = block(JunjietrafficmodModBlocks.TIP_3);
	public static final RegistryObject<Item> TIP_4 = block(JunjietrafficmodModBlocks.TIP_4);
	public static final RegistryObject<Item> TIP_5 = block(JunjietrafficmodModBlocks.TIP_5);
	public static final RegistryObject<Item> TIP_6 = block(JunjietrafficmodModBlocks.TIP_6);
	public static final RegistryObject<Item> TIP_7 = block(JunjietrafficmodModBlocks.TIP_7);
	public static final RegistryObject<Item> TIP_8 = block(JunjietrafficmodModBlocks.TIP_8);
	public static final RegistryObject<Item> TIP_9 = block(JunjietrafficmodModBlocks.TIP_9);
	public static final RegistryObject<Item> TIP_10 = block(JunjietrafficmodModBlocks.TIP_10);
	public static final RegistryObject<Item> TIP_11 = block(JunjietrafficmodModBlocks.TIP_11);
	public static final RegistryObject<Item> TIP_12 = block(JunjietrafficmodModBlocks.TIP_12);
	public static final RegistryObject<Item> TIP_13 = block(JunjietrafficmodModBlocks.TIP_13);
	public static final RegistryObject<Item> TIP_14 = block(JunjietrafficmodModBlocks.TIP_14);
	public static final RegistryObject<Item> WATER_PROTECT_1 = block(JunjietrafficmodModBlocks.WATER_PROTECT_1);
	public static final RegistryObject<Item> WATER_PROTECT_2 = block(JunjietrafficmodModBlocks.WATER_PROTECT_2);
	public static final RegistryObject<Item> WATER_PROTECT_3 = block(JunjietrafficmodModBlocks.WATER_PROTECT_3);
	public static final RegistryObject<Item> WATER_PROTECT_4 = block(JunjietrafficmodModBlocks.WATER_PROTECT_4);
	public static final RegistryObject<Item> GUO_3NOOUT = block(JunjietrafficmodModBlocks.GUO_3NOOUT);
	public static final RegistryObject<Item> TRUCKRIGHT = block(JunjietrafficmodModBlocks.TRUCKRIGHT);
	public static final RegistryObject<Item> CALLPHONE_1 = block(JunjietrafficmodModBlocks.CALLPHONE_1);
	public static final RegistryObject<Item> CALLPHONE_2 = block(JunjietrafficmodModBlocks.CALLPHONE_2);
	public static final RegistryObject<Item> BAD_WEATHER = block(JunjietrafficmodModBlocks.BAD_WEATHER);
	public static final RegistryObject<Item> LAND_SLIDE_AREA = block(JunjietrafficmodModBlocks.LAND_SLIDE_AREA);
	public static final RegistryObject<Item> BRIDGE = block(JunjietrafficmodModBlocks.BRIDGE);
	public static final RegistryObject<Item> EXITREPORT = block(JunjietrafficmodModBlocks.EXITREPORT);
	public static final RegistryObject<Item> NEXTEXIT = block(JunjietrafficmodModBlocks.NEXTEXIT);
	public static final RegistryObject<Item> STRICT_ROAD_2 = block(JunjietrafficmodModBlocks.STRICT_ROAD_2);
	public static final RegistryObject<Item> SERVICE_AREA_ENTRANCE = block(JunjietrafficmodModBlocks.SERVICE_AREA_ENTRANCE);
	public static final RegistryObject<Item> EXIT_NUMBER_SHOW = block(JunjietrafficmodModBlocks.EXIT_NUMBER_SHOW);
	public static final RegistryObject<Item> EXPWY_EXIT_STRAIGHT = block(JunjietrafficmodModBlocks.EXPWY_EXIT_STRAIGHT);
	public static final RegistryObject<Item> EXPWY_EXIT_RIGHT = block(JunjietrafficmodModBlocks.EXPWY_EXIT_RIGHT);
	public static final RegistryObject<Item> ROAD_EXIT_STRAIGHT = block(JunjietrafficmodModBlocks.ROAD_EXIT_STRAIGHT);
	public static final RegistryObject<Item> ROAD_EXIT_RIGHT = block(JunjietrafficmodModBlocks.ROAD_EXIT_RIGHT);
	public static final RegistryObject<Item> GANTRY_G_INTER_STRAIGHT = block(JunjietrafficmodModBlocks.GANTRY_G_INTER_STRAIGHT);
	public static final RegistryObject<Item> GANTRY_G_INTER_RIGHT = block(JunjietrafficmodModBlocks.GANTRY_G_INTER_RIGHT);
	public static final RegistryObject<Item> GANTRY_G_INTER_LEFT = block(JunjietrafficmodModBlocks.GANTRY_G_INTER_LEFT);
	public static final RegistryObject<Item> GANTRY_S_INTER_STRAIGHT = block(JunjietrafficmodModBlocks.GANTRY_S_INTER_STRAIGHT);
	public static final RegistryObject<Item> GANTRY_S_INTER_RIGHT = block(JunjietrafficmodModBlocks.GANTRY_S_INTER_RIGHT);
	public static final RegistryObject<Item> GANTRY_S_INTER_LEFT = block(JunjietrafficmodModBlocks.GANTRY_S_INTER_LEFT);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
