
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mcscjunjie.junzulaki.trafficmod.init;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import mcscjunjie.junzulaki.trafficmod.block.WaterProtect4Block;
import mcscjunjie.junzulaki.trafficmod.block.WaterProtect3Block;
import mcscjunjie.junzulaki.trafficmod.block.WaterProtect2Block;
import mcscjunjie.junzulaki.trafficmod.block.WaterProtect1Block;
import mcscjunjie.junzulaki.trafficmod.block.TruckrightBlock;
import mcscjunjie.junzulaki.trafficmod.block.TlightRBlock;
import mcscjunjie.junzulaki.trafficmod.block.TlightL3Block;
import mcscjunjie.junzulaki.trafficmod.block.TlightL2Block;
import mcscjunjie.junzulaki.trafficmod.block.TlightL1Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight6Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight5Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight4Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight3Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight2Block;
import mcscjunjie.junzulaki.trafficmod.block.Tlight1Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip9Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip8Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip7Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip6Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip5Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip4Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip3Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip2Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip1Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip14Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip13Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip12Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip11Block;
import mcscjunjie.junzulaki.trafficmod.block.Tip10Block;
import mcscjunjie.junzulaki.trafficmod.block.StrictRoadBlock;
import mcscjunjie.junzulaki.trafficmod.block.StrictRoad2Block;
import mcscjunjie.junzulaki.trafficmod.block.StraightArrowSideBlock;
import mcscjunjie.junzulaki.trafficmod.block.StraightArrowBlock;
import mcscjunjie.junzulaki.trafficmod.block.SiderearendBlock;
import mcscjunjie.junzulaki.trafficmod.block.SidekeepspaceBlock;
import mcscjunjie.junzulaki.trafficmod.block.SidedrivetiredlyBlock;
import mcscjunjie.junzulaki.trafficmod.block.ServiceAreaEntranceBlock;
import mcscjunjie.junzulaki.trafficmod.block.SeatbeltBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEweighingstationBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEtunnelBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEtollgate500mBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEtollgate0mBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEnophoneBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEexitnumberBlock;
import mcscjunjie.junzulaki.trafficmod.block.SIDEcross4Block;
import mcscjunjie.junzulaki.trafficmod.block.SIDEcross3Block;
import mcscjunjie.junzulaki.trafficmod.block.SIDEcross2Block;
import mcscjunjie.junzulaki.trafficmod.block.SIDEcross1Block;
import mcscjunjie.junzulaki.trafficmod.block.SIDEbarrierBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadXYBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadSideXYBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadSideSBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadSideGBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadSBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadGBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadExitStraightBlock;
import mcscjunjie.junzulaki.trafficmod.block.RoadExitRightBlock;
import mcscjunjie.junzulaki.trafficmod.block.RightArrowSideBlock;
import mcscjunjie.junzulaki.trafficmod.block.RightArrowBlock;
import mcscjunjie.junzulaki.trafficmod.block.PillarwhiteBlock;
import mcscjunjie.junzulaki.trafficmod.block.PillarblueBlock;
import mcscjunjie.junzulaki.trafficmod.block.PillarSideBlock;
import mcscjunjie.junzulaki.trafficmod.block.PillarCross3Block;
import mcscjunjie.junzulaki.trafficmod.block.NextexitBlock;
import mcscjunjie.junzulaki.trafficmod.block.MileageRXYBlock;
import mcscjunjie.junzulaki.trafficmod.block.MileageRSBlock;
import mcscjunjie.junzulaki.trafficmod.block.MileageRNBlock;
import mcscjunjie.junzulaki.trafficmod.block.MileageRGBlock;
import mcscjunjie.junzulaki.trafficmod.block.MileageRBlock;
import mcscjunjie.junzulaki.trafficmod.block.LimitTruckBlock;
import mcscjunjie.junzulaki.trafficmod.block.LimitEmergencyBlock;
import mcscjunjie.junzulaki.trafficmod.block.LimitCarBlock;
import mcscjunjie.junzulaki.trafficmod.block.LeftArrowSideBlock;
import mcscjunjie.junzulaki.trafficmod.block.LeftArrowBlock;
import mcscjunjie.junzulaki.trafficmod.block.LandSlideAreaBlock;
import mcscjunjie.junzulaki.trafficmod.block.InterchangeB2Block;
import mcscjunjie.junzulaki.trafficmod.block.InterchangeB1Block;
import mcscjunjie.junzulaki.trafficmod.block.InterchangeA2Block;
import mcscjunjie.junzulaki.trafficmod.block.InterchangeA1Block;
import mcscjunjie.junzulaki.trafficmod.block.Interchange2kmBlock;
import mcscjunjie.junzulaki.trafficmod.block.Interchange1kmBlock;
import mcscjunjie.junzulaki.trafficmod.block.HorrearendBlock;
import mcscjunjie.junzulaki.trafficmod.block.HorkeepspaceBlock;
import mcscjunjie.junzulaki.trafficmod.block.Horkeep30Block;
import mcscjunjie.junzulaki.trafficmod.block.Horkeep15Block;
import mcscjunjie.junzulaki.trafficmod.block.Horkeep0Block;
import mcscjunjie.junzulaki.trafficmod.block.HordrivetiredlyBlock;
import mcscjunjie.junzulaki.trafficmod.block.HORplacereportBlock;
import mcscjunjie.junzulaki.trafficmod.block.Guo3nooutBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantrySInterStraightBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantrySInterRightBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantrySInterLeftBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryPillarTopBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryPillarHighBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryPillarBaseBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryPileNumberBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryGInterStraightBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryGInterRightBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryGInterLeftBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryExpwySnumberBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryExpwyGnumberBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryExpwyEndBlock;
import mcscjunjie.junzulaki.trafficmod.block.GantryExpwyBeginBlock;
import mcscjunjie.junzulaki.trafficmod.block.Fwq22Block;
import mcscjunjie.junzulaki.trafficmod.block.Fwq21Block;
import mcscjunjie.junzulaki.trafficmod.block.Fwq1Block;
import mcscjunjie.junzulaki.trafficmod.block.ExpwySBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExpwyGBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExpwyExitStraightBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExpwyExitRightBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitxyBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitsBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitreportBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitrBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitnowBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitnBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitgBlock;
import mcscjunjie.junzulaki.trafficmod.block.ExitNumberShowBlock;
import mcscjunjie.junzulaki.trafficmod.block.Exit500mBlock;
import mcscjunjie.junzulaki.trafficmod.block.Exit3kmBlock;
import mcscjunjie.junzulaki.trafficmod.block.Exit2kmBlock;
import mcscjunjie.junzulaki.trafficmod.block.Exit1kmBlock;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE3rBlock;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE3lBlock;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE3500mBlock;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE2Block;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE1SBlock;
import mcscjunjie.junzulaki.trafficmod.block.EntranceE1GBlock;
import mcscjunjie.junzulaki.trafficmod.block.Cross7Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross6Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross5Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross4Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross3Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross2Block;
import mcscjunjie.junzulaki.trafficmod.block.Cross1Block;
import mcscjunjie.junzulaki.trafficmod.block.Carmodellimitpart2Block;
import mcscjunjie.junzulaki.trafficmod.block.Carmodellimitpart1Block;
import mcscjunjie.junzulaki.trafficmod.block.CarmodellimitAddonBlock;
import mcscjunjie.junzulaki.trafficmod.block.Callphone2Block;
import mcscjunjie.junzulaki.trafficmod.block.Callphone1Block;
import mcscjunjie.junzulaki.trafficmod.block.BridgeBlock;
import mcscjunjie.junzulaki.trafficmod.block.BasswhiteBlock;
import mcscjunjie.junzulaki.trafficmod.block.BassblueBlock;
import mcscjunjie.junzulaki.trafficmod.block.BadWeatherBlock;
import mcscjunjie.junzulaki.trafficmod.JunjietrafficmodMod;

public class JunjietrafficmodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(JunjietrafficmodMod.MODID);
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_1 = REGISTRY.register("tlight_1", () -> new Tlight1Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_2 = REGISTRY.register("tlight_2", () -> new Tlight2Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_3 = REGISTRY.register("tlight_3", () -> new Tlight3Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_4 = REGISTRY.register("tlight_4", () -> new Tlight4Block());
	public static final DeferredHolder<Block, ? extends Block> BASSBLUE = REGISTRY.register("bassblue", () -> new BassblueBlock());
	public static final DeferredHolder<Block, ? extends Block> BASSWHITE = REGISTRY.register("basswhite", () -> new BasswhiteBlock());
	public static final DeferredHolder<Block, ? extends Block> PILLARBLUE = REGISTRY.register("pillarblue", () -> new PillarblueBlock());
	public static final DeferredHolder<Block, ? extends Block> PILLARWHITE = REGISTRY.register("pillarwhite", () -> new PillarwhiteBlock());
	public static final DeferredHolder<Block, ? extends Block> HORDRIVETIREDLY = REGISTRY.register("hordrivetiredly", () -> new HordrivetiredlyBlock());
	public static final DeferredHolder<Block, ? extends Block> HORREAREND = REGISTRY.register("horrearend", () -> new HorrearendBlock());
	public static final DeferredHolder<Block, ? extends Block> HORKEEPSPACE = REGISTRY.register("horkeepspace", () -> new HorkeepspaceBlock());
	public static final DeferredHolder<Block, ? extends Block> HORKEEP_0 = REGISTRY.register("horkeep_0", () -> new Horkeep0Block());
	public static final DeferredHolder<Block, ? extends Block> HORKEEP_15 = REGISTRY.register("horkeep_15", () -> new Horkeep15Block());
	public static final DeferredHolder<Block, ? extends Block> HORKEEP_30 = REGISTRY.register("horkeep_30", () -> new Horkeep30Block());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_2KM = REGISTRY.register("interchange_2km", () -> new Interchange2kmBlock());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_1KM = REGISTRY.register("interchange_1km", () -> new Interchange1kmBlock());
	public static final DeferredHolder<Block, ? extends Block> CARMODELLIMITPART_1 = REGISTRY.register("carmodellimitpart_1", () -> new Carmodellimitpart1Block());
	public static final DeferredHolder<Block, ? extends Block> CARMODELLIMITPART_2 = REGISTRY.register("carmodellimitpart_2", () -> new Carmodellimitpart2Block());
	public static final DeferredHolder<Block, ? extends Block> CARMODELLIMIT_ADDON = REGISTRY.register("carmodellimit_addon", () -> new CarmodellimitAddonBlock());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_5 = REGISTRY.register("tlight_5", () -> new Tlight5Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_6 = REGISTRY.register("tlight_6", () -> new Tlight6Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_R = REGISTRY.register("tlight_r", () -> new TlightRBlock());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_L_1 = REGISTRY.register("tlight_l_1", () -> new TlightL1Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_L_2 = REGISTRY.register("tlight_l_2", () -> new TlightL2Block());
	public static final DeferredHolder<Block, ? extends Block> TLIGHT_L_3 = REGISTRY.register("tlight_l_3", () -> new TlightL3Block());
	public static final DeferredHolder<Block, ? extends Block> PILLAR_CROSS_3 = REGISTRY.register("pillar_cross_3", () -> new PillarCross3Block());
	public static final DeferredHolder<Block, ? extends Block> PILLAR_SIDE = REGISTRY.register("pillar_side", () -> new PillarSideBlock());
	public static final DeferredHolder<Block, ? extends Block> SIDEDRIVETIREDLY = REGISTRY.register("sidedrivetiredly", () -> new SidedrivetiredlyBlock());
	public static final DeferredHolder<Block, ? extends Block> SIDEREAREND = REGISTRY.register("siderearend", () -> new SiderearendBlock());
	public static final DeferredHolder<Block, ? extends Block> SIDEKEEPSPACE = REGISTRY.register("sidekeepspace", () -> new SidekeepspaceBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_PILLAR_BASE = REGISTRY.register("gantry_pillar_base", () -> new GantryPillarBaseBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_PILLAR_HIGH = REGISTRY.register("gantry_pillar_high", () -> new GantryPillarHighBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITG = REGISTRY.register("exitg", () -> new ExitgBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITS = REGISTRY.register("exits", () -> new ExitsBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITXY = REGISTRY.register("exitxy", () -> new ExitxyBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITR = REGISTRY.register("exitr", () -> new ExitrBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITN = REGISTRY.register("exitn", () -> new ExitnBlock());
	public static final DeferredHolder<Block, ? extends Block> EXIT_3KM = REGISTRY.register("exit_3km", () -> new Exit3kmBlock());
	public static final DeferredHolder<Block, ? extends Block> EXIT_2KM = REGISTRY.register("exit_2km", () -> new Exit2kmBlock());
	public static final DeferredHolder<Block, ? extends Block> EXIT_1KM = REGISTRY.register("exit_1km", () -> new Exit1kmBlock());
	public static final DeferredHolder<Block, ? extends Block> EXIT_500M = REGISTRY.register("exit_500m", () -> new Exit500mBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITNOW = REGISTRY.register("exitnow", () -> new ExitnowBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_G = REGISTRY.register("road_g", () -> new RoadGBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_S = REGISTRY.register("road_s", () -> new RoadSBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_XY = REGISTRY.register("road_xy", () -> new RoadXYBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_SIDE_G = REGISTRY.register("road_side_g", () -> new RoadSideGBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_SIDE_S = REGISTRY.register("road_side_s", () -> new RoadSideSBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_SIDE_XY = REGISTRY.register("road_side_xy", () -> new RoadSideXYBlock());
	public static final DeferredHolder<Block, ? extends Block> EXPWY_G = REGISTRY.register("expwy_g", () -> new ExpwyGBlock());
	public static final DeferredHolder<Block, ? extends Block> EXPWY_S = REGISTRY.register("expwy_s", () -> new ExpwySBlock());
	public static final DeferredHolder<Block, ? extends Block> MILEAGE_R = REGISTRY.register("mileage_r", () -> new MileageRBlock());
	public static final DeferredHolder<Block, ? extends Block> MILEAGE_RG = REGISTRY.register("mileage_rg", () -> new MileageRGBlock());
	public static final DeferredHolder<Block, ? extends Block> MILEAGE_RS = REGISTRY.register("mileage_rs", () -> new MileageRSBlock());
	public static final DeferredHolder<Block, ? extends Block> MILEAGE_RXY = REGISTRY.register("mileage_rxy", () -> new MileageRXYBlock());
	public static final DeferredHolder<Block, ? extends Block> MILEAGE_RN = REGISTRY.register("mileage_rn", () -> new MileageRNBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_PILLAR_TOP = REGISTRY.register("gantry_pillar_top", () -> new GantryPillarTopBlock());
	public static final DeferredHolder<Block, ? extends Block> LIMIT_CAR = REGISTRY.register("limit_car", () -> new LimitCarBlock());
	public static final DeferredHolder<Block, ? extends Block> LIMIT_TRUCK = REGISTRY.register("limit_truck", () -> new LimitTruckBlock());
	public static final DeferredHolder<Block, ? extends Block> LIMIT_EMERGENCY = REGISTRY.register("limit_emergency", () -> new LimitEmergencyBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_PILE_NUMBER = REGISTRY.register("gantry_pile_number", () -> new GantryPileNumberBlock());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_1_G = REGISTRY.register("entrance_e_1_g", () -> new EntranceE1GBlock());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_1_S = REGISTRY.register("entrance_e_1_s", () -> new EntranceE1SBlock());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_2 = REGISTRY.register("entrance_e_2", () -> new EntranceE2Block());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_3500M = REGISTRY.register("entrance_e_3500m", () -> new EntranceE3500mBlock());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_3R = REGISTRY.register("entrance_e_3r", () -> new EntranceE3rBlock());
	public static final DeferredHolder<Block, ? extends Block> ENTRANCE_E_3L = REGISTRY.register("entrance_e_3l", () -> new EntranceE3lBlock());
	public static final DeferredHolder<Block, ? extends Block> FWQ_1 = REGISTRY.register("fwq_1", () -> new Fwq1Block());
	public static final DeferredHolder<Block, ? extends Block> FWQ_21 = REGISTRY.register("fwq_21", () -> new Fwq21Block());
	public static final DeferredHolder<Block, ? extends Block> FWQ_22 = REGISTRY.register("fwq_22", () -> new Fwq22Block());
	public static final DeferredHolder<Block, ? extends Block> LEFT_ARROW = REGISTRY.register("left_arrow", () -> new LeftArrowBlock());
	public static final DeferredHolder<Block, ? extends Block> LEFT_ARROW_SIDE = REGISTRY.register("left_arrow_side", () -> new LeftArrowSideBlock());
	public static final DeferredHolder<Block, ? extends Block> RIGHT_ARROW = REGISTRY.register("right_arrow", () -> new RightArrowBlock());
	public static final DeferredHolder<Block, ? extends Block> RIGHT_ARROW_SIDE = REGISTRY.register("right_arrow_side", () -> new RightArrowSideBlock());
	public static final DeferredHolder<Block, ? extends Block> STRAIGHT_ARROW = REGISTRY.register("straight_arrow", () -> new StraightArrowBlock());
	public static final DeferredHolder<Block, ? extends Block> STRAIGHT_ARROW_SIDE = REGISTRY.register("straight_arrow_side", () -> new StraightArrowSideBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_EXPWY_GNUMBER = REGISTRY.register("gantry_expwy_gnumber", () -> new GantryExpwyGnumberBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_EXPWY_SNUMBER = REGISTRY.register("gantry_expwy_snumber", () -> new GantryExpwySnumberBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_EXPWY_BEGIN = REGISTRY.register("gantry_expwy_begin", () -> new GantryExpwyBeginBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_EXPWY_END = REGISTRY.register("gantry_expwy_end", () -> new GantryExpwyEndBlock());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_A_1 = REGISTRY.register("interchange_a_1", () -> new InterchangeA1Block());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_A_2 = REGISTRY.register("interchange_a_2", () -> new InterchangeA2Block());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_B_1 = REGISTRY.register("interchange_b_1", () -> new InterchangeB1Block());
	public static final DeferredHolder<Block, ? extends Block> INTERCHANGE_B_2 = REGISTRY.register("interchange_b_2", () -> new InterchangeB2Block());
	public static final DeferredHolder<Block, ? extends Block> SEATBELT = REGISTRY.register("seatbelt", () -> new SeatbeltBlock());
	public static final DeferredHolder<Block, ? extends Block> HO_RPLACEREPORT = REGISTRY.register("ho_rplacereport", () -> new HORplacereportBlock());
	public static final DeferredHolder<Block, ? extends Block> STRICT_ROAD = REGISTRY.register("strict_road", () -> new StrictRoadBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_ECROSS_1 = REGISTRY.register("sid_ecross_1", () -> new SIDEcross1Block());
	public static final DeferredHolder<Block, ? extends Block> SID_ECROSS_2 = REGISTRY.register("sid_ecross_2", () -> new SIDEcross2Block());
	public static final DeferredHolder<Block, ? extends Block> SID_ECROSS_3 = REGISTRY.register("sid_ecross_3", () -> new SIDEcross3Block());
	public static final DeferredHolder<Block, ? extends Block> SID_ECROSS_4 = REGISTRY.register("sid_ecross_4", () -> new SIDEcross4Block());
	public static final DeferredHolder<Block, ? extends Block> SID_ENOPHONE = REGISTRY.register("sid_enophone", () -> new SIDEnophoneBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_ETOLLGATE_500M = REGISTRY.register("sid_etollgate_500m", () -> new SIDEtollgate500mBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_ETOLLGATE_0M = REGISTRY.register("sid_etollgate_0m", () -> new SIDEtollgate0mBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_EWEIGHINGSTATION = REGISTRY.register("sid_eweighingstation", () -> new SIDEweighingstationBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_EBARRIER = REGISTRY.register("sid_ebarrier", () -> new SIDEbarrierBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_ETUNNEL = REGISTRY.register("sid_etunnel", () -> new SIDEtunnelBlock());
	public static final DeferredHolder<Block, ? extends Block> SID_EEXITNUMBER = REGISTRY.register("sid_eexitnumber", () -> new SIDEexitnumberBlock());
	public static final DeferredHolder<Block, ? extends Block> CROSS_1 = REGISTRY.register("cross_1", () -> new Cross1Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_2 = REGISTRY.register("cross_2", () -> new Cross2Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_3 = REGISTRY.register("cross_3", () -> new Cross3Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_4 = REGISTRY.register("cross_4", () -> new Cross4Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_5 = REGISTRY.register("cross_5", () -> new Cross5Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_6 = REGISTRY.register("cross_6", () -> new Cross6Block());
	public static final DeferredHolder<Block, ? extends Block> CROSS_7 = REGISTRY.register("cross_7", () -> new Cross7Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_1 = REGISTRY.register("tip_1", () -> new Tip1Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_2 = REGISTRY.register("tip_2", () -> new Tip2Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_3 = REGISTRY.register("tip_3", () -> new Tip3Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_4 = REGISTRY.register("tip_4", () -> new Tip4Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_5 = REGISTRY.register("tip_5", () -> new Tip5Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_6 = REGISTRY.register("tip_6", () -> new Tip6Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_7 = REGISTRY.register("tip_7", () -> new Tip7Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_8 = REGISTRY.register("tip_8", () -> new Tip8Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_9 = REGISTRY.register("tip_9", () -> new Tip9Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_10 = REGISTRY.register("tip_10", () -> new Tip10Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_11 = REGISTRY.register("tip_11", () -> new Tip11Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_12 = REGISTRY.register("tip_12", () -> new Tip12Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_13 = REGISTRY.register("tip_13", () -> new Tip13Block());
	public static final DeferredHolder<Block, ? extends Block> TIP_14 = REGISTRY.register("tip_14", () -> new Tip14Block());
	public static final DeferredHolder<Block, ? extends Block> WATER_PROTECT_1 = REGISTRY.register("water_protect_1", () -> new WaterProtect1Block());
	public static final DeferredHolder<Block, ? extends Block> WATER_PROTECT_2 = REGISTRY.register("water_protect_2", () -> new WaterProtect2Block());
	public static final DeferredHolder<Block, ? extends Block> WATER_PROTECT_3 = REGISTRY.register("water_protect_3", () -> new WaterProtect3Block());
	public static final DeferredHolder<Block, ? extends Block> WATER_PROTECT_4 = REGISTRY.register("water_protect_4", () -> new WaterProtect4Block());
	public static final DeferredHolder<Block, ? extends Block> GUO_3NOOUT = REGISTRY.register("guo_3noout", () -> new Guo3nooutBlock());
	public static final DeferredHolder<Block, ? extends Block> TRUCKRIGHT = REGISTRY.register("truckright", () -> new TruckrightBlock());
	public static final DeferredHolder<Block, ? extends Block> CALLPHONE_1 = REGISTRY.register("callphone_1", () -> new Callphone1Block());
	public static final DeferredHolder<Block, ? extends Block> CALLPHONE_2 = REGISTRY.register("callphone_2", () -> new Callphone2Block());
	public static final DeferredHolder<Block, ? extends Block> BAD_WEATHER = REGISTRY.register("bad_weather", () -> new BadWeatherBlock());
	public static final DeferredHolder<Block, ? extends Block> LAND_SLIDE_AREA = REGISTRY.register("land_slide_area", () -> new LandSlideAreaBlock());
	public static final DeferredHolder<Block, ? extends Block> BRIDGE = REGISTRY.register("bridge", () -> new BridgeBlock());
	public static final DeferredHolder<Block, ? extends Block> EXITREPORT = REGISTRY.register("exitreport", () -> new ExitreportBlock());
	public static final DeferredHolder<Block, ? extends Block> NEXTEXIT = REGISTRY.register("nextexit", () -> new NextexitBlock());
	public static final DeferredHolder<Block, ? extends Block> STRICT_ROAD_2 = REGISTRY.register("strict_road_2", () -> new StrictRoad2Block());
	public static final DeferredHolder<Block, ? extends Block> SERVICE_AREA_ENTRANCE = REGISTRY.register("service_area_entrance", () -> new ServiceAreaEntranceBlock());
	public static final DeferredHolder<Block, ? extends Block> EXIT_NUMBER_SHOW = REGISTRY.register("exit_number_show", () -> new ExitNumberShowBlock());
	public static final DeferredHolder<Block, ? extends Block> EXPWY_EXIT_STRAIGHT = REGISTRY.register("expwy_exit_straight", () -> new ExpwyExitStraightBlock());
	public static final DeferredHolder<Block, ? extends Block> EXPWY_EXIT_RIGHT = REGISTRY.register("expwy_exit_right", () -> new ExpwyExitRightBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_EXIT_STRAIGHT = REGISTRY.register("road_exit_straight", () -> new RoadExitStraightBlock());
	public static final DeferredHolder<Block, ? extends Block> ROAD_EXIT_RIGHT = REGISTRY.register("road_exit_right", () -> new RoadExitRightBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_G_INTER_STRAIGHT = REGISTRY.register("gantry_g_inter_straight", () -> new GantryGInterStraightBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_G_INTER_RIGHT = REGISTRY.register("gantry_g_inter_right", () -> new GantryGInterRightBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_G_INTER_LEFT = REGISTRY.register("gantry_g_inter_left", () -> new GantryGInterLeftBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_S_INTER_STRAIGHT = REGISTRY.register("gantry_s_inter_straight", () -> new GantrySInterStraightBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_S_INTER_RIGHT = REGISTRY.register("gantry_s_inter_right", () -> new GantrySInterRightBlock());
	public static final DeferredHolder<Block, ? extends Block> GANTRY_S_INTER_LEFT = REGISTRY.register("gantry_s_inter_left", () -> new GantrySInterLeftBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
